# Generated by Django 4.2 on 2024-01-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
